### ISSUE TITLE
E: Failed to get tx meta from txpool

### ISSUE THREAD

**Issue by ilie1988** [moneroexamples/openmonero#169] opened 2020-03-01 11:55 UTC
I;m getting this error sometimes after a couple of hours, i think you should be able to replicate it, leave it running on a chain were there are many transactions coming in, if i restart the openmonero the error disappears, i have merged the devel branch and the error persists anyways

![image](https://user-images.githubusercontent.com/56231050/75625179-e8be0280-5bbb-11ea-9509-888e3df578f7.png)

**Comment by moneroexamples** [comment] 2020-03-01 23:30
Thanks, I will try to look into that, but not sure when. If I find resolution to the issue, I will let you know.

**Comment by moneroexamples** [comment] 2020-03-03 10:39
Trying to reproduce. This happens on mainnet, testnet or stagenet? 

Also, by "there are many transactions coming in" you mean transactions coming to you?

**Comment by ilie1988** [comment] 2020-03-03 12:21
i think is because i omitted some commits for pruned nodes, if in your test all goes well then it was just on my end, the referenced issue above breaks my online wallet txpool search, by many transaction i ment that you have transactions send from online wallet

**Comment by moneroexamples** [comment] 2020-03-04 10:12
I will reopen it for now. 

For future reference: The error originates from https://github.com/monero-project/monero/blob/159c78758af0a0af9df9a4f9ab81888f9322e9be/src/blockchain_db/blockchain_db.cpp#L992

**Comment by ilie1988** [comment] 2020-03-11 10:47
> I will reopen it for now.
> 
> For future reference: The error originates from https://github.com/monero-project/monero/blob/159c78758af0a0af9df9a4f9ab81888f9322e9be/src/blockchain_db/blockchain_db.cpp#L992

https://github.com/monero-project/monero/commit/5d7ae2d2791c0244a221872a7ac62627abb81896 this is the commit that breaks the txpool, i remember we had some issues on GUI because of it

**Comment by moneroexamples** [comment] 2020-03-11 13:23
Thank you. Will look into it.

**Comment by moneroexamples** [comment] 2020-03-12 00:32
Cloud you clarify which monero branch/version you are using? Will try to setup everything same to replicate the issue.

**Comment by ilie1988** [comment] 2020-03-12 09:54
I used the Devel branch, it happens after a while after you run openmonero, be on a chain with many transactions, i don't know why sometimes it happens and sometimes i won't, about the explorer was this issue https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/202

**Comment by moneroexamples** [comment] 2020-03-12 12:45
Just for my reference: 

The error originates here: https://github.com/monero-project/monero/blob/159c78758af0a0af9df9a4f9ab81888f9322e9be/src/blockchain_db/blockchain_db.cpp#L997

Due to false in: https://github.com/monero-project/monero/blob/8eedc8a390c73112af9fff712a47c2c1814bc16a/src/blockchain_db/lmdb/db_lmdb.cpp#L1840

**Comment by moneroexamples** [comment] 2020-03-14 06:32
I put the fix in this branch for testing https://github.com/moneroexamples/openmonero/tree/fix_txpool

**Comment by ilie1988** [comment] 2020-03-14 17:43
> I put the fix in this branch for testing https://github.com/moneroexamples/openmonero/tree/fix_txpool

This tree `fix_txpool` won't compile with latest monero, you need to add the fixes from devel branch, i cherry-picked the commit `Fix for Failed to get tx meta from txpool` and so far the error doesn't show up anymore, i will keep you updated with the results after more tests :)

**Comment by moneroexamples** [comment] 2020-03-14 23:39
By `latest monero` monero you mean its master branch? I use monero master branch, and haven't observed compilation issues with the branch.

**Comment by ilie1988** [comment] 2020-03-15 08:37
> By `latest monero` monero you mean its master branch? I use monero master branch, and haven't observed compilation issues with the branch.

Yes the monero master branch, i needed to pull `xmregcore` and merge devel for it to compile.

**Comment by moneroexamples** [comment] 2020-03-15 08:41
Using `git pull --recurse-submodules` should pull latest `xmregcore` as well.

**Comment by ilie1988** [comment] 2020-03-15 08:53
> Using `git pull --recurse-submodules` should pull latest `xmregcore` as well.

True, i did it manually as i didn't knew that i had to pull `xmergcore` to, so far no error of `TxPool` it looks like it got fixed with your fix :)

**Comment by ilie1988** [comment] 2020-03-15 08:57
Another question, does this https://github.com/moneroexamples/openmonero/blob/master/src/utils.cpp#L726 even gets used at this point? As it uses the `xmregcore` for it

**Comment by moneroexamples** [comment] 2020-03-15 10:22
There is still plenty of references to `RCTTypeSimple` in monero codebase https://github.com/monero-project/monero/search?p=1&q=RCTTypeSimple&unscoped_q=RCTTypeSimple so I haven't removed it.

**Comment by ilie1988** [comment] 2020-03-15 10:30
> There is still plenty of references to `RCTTypeSimple` in monero codebase >https://github.com/monero-project/monero/search?p=1&q=RCTTypeSimple&unscoped_q=RCTTypeSimple so I haven't removed it.

True, looks good so far, should i close the Issue? I don't get the error anymore

**Comment by moneroexamples** [comment] 2020-03-15 21:22
You can leave it open for a bit more for visibility. Once I merge the branch into `devel` branch I can close the issue myself.

**Closed** 2020-03-24 10:09 UTC
